### ISSUE TITLE
How do I use this package with a 16-line LIDAR?

### ISSUE THREAD

**Issue by yicheng6o6** [TuSimple/LiDAR_SOT#12]
Hi,
Thank you for your great work.

I have a VLP-16 lidar sensor and I want to use it to detect pedestrian in ROS. What should I do to take my lidar data to use this package?

I would be grateful if you could give me some suggestions to achieve it.

Best wishes,
Yicheng

**Comment by Lzc6996** [comment]
Hi, @yicheng6o6 
Thanks for your interesting.

Actually, our package only does tracking task instead of 3D detection.
If you want to detect some objects, [mmdet3D](https://github.com/open-mmlab/mmdetection3d) may be a better choice.
