### ISSUE TITLE
One question about ICP Loss and Shape loss

### ISSUE THREAD

**Issue by aiming1998** [TuSimple/LiDAR_SOT#13]
@ziqipang  Hello, thank you very much for sharing the open source code and your article. After reading your paper carefully, I have a question that is very curious. Is there any difference between  shape_loss  in  L2 loss  and   icp_loss  , I think the two loss seems to be the same. I would appreciate it if you could answer this question.

**Comment by ziqipang** [comment]
Hi, thanks for your interest in our work! Here is a brief explanation of the differences.

ICP loss computes the registration loss between two adjacent point cloud frames, say, frame t-1 and frame t. However, the shape loss computes the registration loss between the latest point cloud and the shape of the object, say the point cloud in frame t and the point cloud of the object. In practice, the shape of the object comes from multiple point clouds, such as the point cloud in the first frame or the aggregation of point clouds from the first frame.

**Comment by ziqipang** [comment]
@Joeless Please check the answer above and see if that solved your question.
