### ISSUE TITLE
AttributeError: num_lidar_points_in_box

### ISSUE THREAD

**Issue by newbie521** [TuSimple/LiDAR_SOT#15]
Hello, I would like to ask, I have a problem with processing the data and the process, it is in the gt_info.py the following problem occurs
![image](https://github.com/tusen-ai/LiDAR_SOT/assets/61658896/3da35854-6db6-4b8c-9756-62e6297a6da6)
I'm not sure if it's a version issue or a problem with my dataset. Below is my package environment, I hope some big guy can reply me, thanks a lot!
![image](https://github.com/tusen-ai/LiDAR_SOT/assets/61658896/09fda186-ab03-4002-a78b-4e5f8a037cb1)

**Comment by Lzc6996** [comment]
@newbie521 
Your version of the Waymo Open Dataset seems outdated. You might want to try version 1.6.1, which should include the field you're looking for. You can find more information about this field in the label.proto at the [Waymo Open Dataset GitHub repository](https://github.com/waymo-research/waymo-open-dataset/blob/36529372c6aec153e96ae8e928deacfdf7479c5f/src/waymo_open_dataset/label.proto#L87).

**Comment by newbie521** [comment]
> @newbie521 Your version of the Waymo Open Dataset seems outdated. You might want to try version 1.6.1, which should include the field you're looking for. You can find more information about this field in the label.proto at the [Waymo Open Dataset GitHub repository](https://github.com/waymo-research/waymo-open-dataset/blob/36529372c6aec153e96ae8e928deacfdf7479c5f/src/waymo_open_dataset/label.proto#L87).

Thank you for replying to my question on your busy schedule, I will try it on my own later.

**Comment by Lzc6996** [comment]
Hi, @newbie521 
just checking in to see how it's going?
